export interface Bank {
  id: string
  name: string
  code: string
  type: 'commercial' | 'fintech' | 'mfb'
}

export const NIGERIAN_BANKS: Bank[] = [
  // Commercial Banks
  { id: '1', name: 'Access Bank', code: '044', type: 'commercial' },
  { id: '2', name: 'First Bank of Nigeria', code: '011', type: 'commercial' },
  { id: '3', name: 'Guaranty Trust Bank (GTBank)', code: '058', type: 'commercial' },
  { id: '4', name: 'United Bank for Africa (UBA)', code: '033', type: 'commercial' },
  { id: '5', name: 'Zenith Bank', code: '057', type: 'commercial' },
  { id: '6', name: 'Fidelity Bank', code: '070', type: 'commercial' },
  { id: '7', name: 'FCMB (First City Monument Bank)', code: '214', type: 'commercial' },
  { id: '8', name: 'Stanbic IBTC Bank', code: '221', type: 'commercial' },
  { id: '9', name: 'Sterling Bank', code: '232', type: 'commercial' },
  { id: '10', name: 'Union Bank of Nigeria', code: '032', type: 'commercial' },
  { id: '11', name: 'Wema Bank', code: '035', type: 'commercial' },
  { id: '12', name: 'Ecobank Nigeria', code: '050', type: 'commercial' },
  { id: '13', name: 'Polaris Bank', code: '076', type: 'commercial' },
  { id: '14', name: 'Keystone Bank', code: '082', type: 'commercial' },
  { id: '15', name: 'Titan Trust Bank', code: '102', type: 'commercial' },
  { id: '16', name: 'Globus Bank', code: '103', type: 'commercial' },
  { id: '17', name: 'Optimus Bank', code: '107', type: 'commercial' },
  { id: '18', name: 'Parallex Bank', code: '526', type: 'commercial' },
  { id: '19', name: 'Premium Trust Bank', code: '105', type: 'commercial' },
  { id: '20', name: 'Providus Bank', code: '101', type: 'commercial' },
  { id: '21', name: 'SunTrust Bank', code: '100', type: 'commercial' },
  { id: '22', name: 'Heritage Bank', code: '030', type: 'commercial' },
  { id: '23', name: 'Unity Bank', code: '215', type: 'commercial' },
  { id: '24', name: 'Jaiz Bank', code: '301', type: 'commercial' },
  { id: '25', name: 'TAJBank', code: '302', type: 'commercial' },
  { id: '26', name: 'Lotus Bank', code: '303', type: 'commercial' },
  { id: '27', name: 'Signature Bank', code: '106', type: 'commercial' },

  // Fintech, Digital Banks & Payment Service Banks
  { id: '100', name: 'OPay', code: '999992', type: 'fintech' },
  { id: '101', name: 'PalmPay', code: '999991', type: 'fintech' },
  { id: '102', name: 'Moniepoint Microfinance Bank', code: '50515', type: 'fintech' },
  { id: '103', name: 'Kuda Bank', code: '50211', type: 'fintech' },
  { id: '104', name: 'VFD Microfinance Bank (Vbank)', code: '566', type: 'fintech' },
  { id: '105', name: 'FairMoney Microfinance Bank', code: '51318', type: 'fintech' },
  { id: '106', name: 'Carbon (Paylater)', code: '565', type: 'fintech' },
  { id: '107', name: 'SmartCash Payment Service Bank', code: '120002', type: 'fintech' },
  { id: '108', name: 'MoMo Payment Service Bank (MTN)', code: '120003', type: 'fintech' },
  { id: '109', name: '9PSB (9mobile)', code: '120001', type: 'fintech' },
  { id: '110', name: 'HopePSB', code: '120004', type: 'fintech' },
  { id: '111', name: 'Paystack Titan', code: '100039', type: 'fintech' },
  { id: '112', name: 'MoreMonee', code: '50951', type: 'fintech' },
  { id: '113', name: 'Gomoney', code: '100022', type: 'fintech' },
  { id: '114', name: 'Rubies Bank', code: '125', type: 'fintech' },
  { id: '115', name: 'Sparkle Microfinance Bank', code: '51310', type: 'fintech' },
  { id: '116', name: 'Eyowo', code: '50123', type: 'fintech' },
  { id: '117', name: 'Dot Microfinance Bank', code: '50163', type: 'fintech' },
  { id: '118', name: 'Nomba (Kudi)', code: '100032', type: 'fintech' },
  { id: '119', name: 'Paga', code: '100002', type: 'fintech' },
  { id: '120', name: 'Raven Bank', code: '51311', type: 'fintech' },
  { id: '121', name: 'Rex Microfinance Bank', code: '50200', type: 'fintech' },
  { id: '122', name: 'Pocket by PiggyVest', code: '51251', type: 'fintech' },
  { id: '123', name: 'Flutterwave Barter', code: '100003', type: 'fintech' },
  { id: '124', name: 'Readycash', code: '100005', type: 'fintech' },
  { id: '125', name: 'MKobo Microfinance Bank', code: '50561', type: 'fintech' },
  { id: '126', name: 'Branch International', code: '50205', type: 'fintech' },
  { id: '127', name: 'Fincra', code: '100040', type: 'fintech' },
  { id: '128', name: 'Parkway - ReadyCash', code: '311', type: 'fintech' },
  { id: '129', name: 'Cellulant', code: '100005', type: 'fintech' },
  { id: '130', name: 'Kongapay', code: '100025', type: 'fintech' },
  { id: '131', name: 'VTNetwork', code: '100012', type: 'fintech' },
  { id: '132', name: 'eTranzact', code: '100006', type: 'fintech' },
  { id: '133', name: 'One Finance', code: '565', type: 'fintech' },

  // Microfinance Banks (MFB)
  { id: '200', name: 'Abbey Mortgage Bank', code: '401', type: 'mfb' },
  { id: '201', name: 'Above Microfinance Bank', code: '51204', type: 'mfb' },
  { id: '202', name: 'Accion Microfinance Bank', code: '602', type: 'mfb' },
  { id: '203', name: 'Ameiran Microfinance Bank', code: '50926', type: 'mfb' },
  { id: '204', name: 'AMJU Unique MFB', code: '50931', type: 'mfb' },
  { id: '205', name: 'Aramoko MFB', code: '50083', type: 'mfb' },
  { id: '206', name: 'ASO Savings and Loans', code: '402', type: 'mfb' },
  { id: '207', name: 'Bainescredit MFB', code: '51229', type: 'mfb' },
  { id: '208', name: 'Bowen Microfinance Bank', code: '50932', type: 'mfb' },
  { id: '209', name: 'CEMCS Microfinance Bank', code: '50823', type: 'mfb' },
  { id: '210', name: 'Chanelle Bank', code: '50171', type: 'mfb' },
  { id: '211', name: 'Chicum Microfinance Bank', code: '50800', type: 'mfb' },
  { id: '212', name: 'Corestep MFB', code: '50204', type: 'mfb' },
  { id: '213', name: 'Covenant MFB', code: '50739', type: 'mfb' },
  { id: '214', name: 'Credit Afrique MFB', code: '50828', type: 'mfb' },
  { id: '215', name: 'Daylight Microfinance Bank', code: '50181', type: 'mfb' },
  { id: '216', name: 'Empire Trust MFB', code: '50228', type: 'mfb' },
  { id: '217', name: 'FinaTrust Microfinance Bank', code: '50230', type: 'mfb' },
  { id: '218', name: 'First Option MFB', code: '50280', type: 'mfb' },
  { id: '219', name: 'GTI Microfinance Bank', code: '50389', type: 'mfb' },
  { id: '220', name: 'Hasal Microfinance Bank', code: '50383', type: 'mfb' },
  { id: '221', name: 'Infinity MFB', code: '50439', type: 'mfb' },
  { id: '222', name: 'Kadpoly MFB', code: '50502', type: 'mfb' },
  { id: '223', name: 'Lapo Microfinance Bank', code: '50549', type: 'mfb' },
  { id: '224', name: 'Mayfair MFB', code: '50563', type: 'mfb' },
  { id: '225', name: 'Mint Finex MFB', code: '50304', type: 'mfb' },
  { id: '226', name: 'Mutual Trust Microfinance Bank', code: '50670', type: 'mfb' },
  { id: '227', name: 'NPF Microfinance Bank', code: '50629', type: 'mfb' },
  { id: '228', name: 'Parapo MFB', code: '50711', type: 'mfb' },
  { id: '229', name: 'Peace Microfinance Bank', code: '50713', type: 'mfb' },
  { id: '230', name: 'PecanTrust Microfinance Bank', code: '50722', type: 'mfb' },
  { id: '231', name: 'Personal Trust MFB', code: '51146', type: 'mfb' },
  { id: '232', name: 'Petra MFB', code: '50746', type: 'mfb' },
  { id: '233', name: 'QuickFund MFB', code: '50775', type: 'mfb' },
  { id: '234', name: 'Rahama MFB', code: '50779', type: 'mfb' },
  { id: '235', name: 'Reliance MFB', code: '50791', type: 'mfb' },
  { id: '236', name: 'Renmoney MFB', code: '50992', type: 'mfb' },
  { id: '237', name: 'Safe Haven MFB', code: '51113', type: 'mfb' },
  { id: '238', name: 'Seedvest MFB', code: '50809', type: 'mfb' },
  { id: '239', name: 'Shepherd Trust MFB', code: '50840', type: 'mfb' },
  { id: '240', name: 'Supreme MFB', code: '50870', type: 'mfb' },
  { id: '241', name: 'Tangerine Money', code: '51269', type: 'mfb' },
  { id: '242', name: 'TCF MFB', code: '51211', type: 'mfb' },
  { id: '243', name: 'Unical MFB', code: '50868', type: 'mfb' },
  { id: '244', name: 'Unaab MFB', code: '50867', type: 'mfb' },
  { id: '245', name: 'Xslnce MFB', code: '50949', type: 'mfb' },
  { id: '246', name: 'Al-Barakah MFB', code: '50081', type: 'mfb' },
  { id: '247', name: 'Apex Trust MFB', code: '50092', type: 'mfb' },
  { id: '248', name: 'Baobab Microfinance Bank', code: '50111', type: 'mfb' },
  { id: '249', name: 'BOI Microfinance Bank', code: '50117', type: 'mfb' },
  { id: '250', name: 'CapitalMetriq Swift MFB', code: '50890', type: 'mfb' },
  { id: '251', name: 'Federal University Technology Minna MFB', code: '50260', type: 'mfb' },
  { id: '252', name: 'First Royal Microfinance Bank', code: '50282', type: 'mfb' },
  { id: '253', name: 'Gashua Microfinance Bank', code: '50314', type: 'mfb' },
  { id: '254', name: 'GTI Microfinance Bank', code: '50389', type: 'mfb' },
  { id: '255', name: 'Imo State Microfinance Bank', code: '50422', type: 'mfb' },
  { id: '256', name: 'Mainstreet Microfinance Bank', code: '50558', type: 'mfb' },
  { id: '257', name: 'Microvis Microfinance Bank', code: '50568', type: 'mfb' },
  { id: '258', name: 'Nwannegadi Microfinance Bank', code: '50648', type: 'mfb' },
  { id: '259', name: 'Ohafia Microfinance Bank', code: '50663', type: 'mfb' },
  { id: '260', name: 'Parkway Microfinance Bank', code: '50692', type: 'mfb' },
  { id: '261', name: 'Rigo Microfinance Bank', code: '51286', type: 'mfb' },
  { id: '262', name: 'Royal Exchange Microfinance Bank', code: '50785', type: 'mfb' },
  { id: '263', name: 'Shield Microfinance Bank', code: '50811', type: 'mfb' },
  { id: '264', name: 'Slingshot Microfinance Bank', code: '51314', type: 'mfb' },
  { id: '265', name: 'Stellas Microfinance Bank', code: '50854', type: 'mfb' },
  { id: '266', name: 'Trustbond Mortgage Bank', code: '523', type: 'mfb' },
  { id: '267', name: 'U&C Microfinance Bank', code: '50862', type: 'mfb' },
  { id: '268', name: 'Umuchinemere Procredit MFB', code: '50865', type: 'mfb' },
  { id: '269', name: 'Virtue Microfinance Bank', code: '50889', type: 'mfb' },
  { id: '270', name: 'Yes Microfinance Bank', code: '50942', type: 'mfb' }
]
